# .github/workflows/main.yml

name: Update Billing Sheet

on:
  repository_dispatch:
    types: [billing] # This must match the 'event_type' from your Apps Script

jobs:
  build-and-run-update:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas gspread oauth2client

    - name: Run the Python script
      env:
        # These values are passed from the Apps Script payload
        NEW_DATA_SHEET_ID: ${{ github.event.client_payload.new_data_sheet_id }}
        MAIN_SHEET_ID: ${{ github.event.client_payload.main_sheet_id }}
        # This secret must be configured in your GitHub repository settings
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
      run: python process_billing.py # This must match your Python script's filename
